version: '3.8'

services:
  api_service:
    hostname: constructor_service
    container_name: constructor_service_service
    image: ghcr.io/digitable-team/constructor-service:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    restart: on-failure
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - /usr/src/app/node_modules