version: '3.8'

services:
  constructor_service:
    container_name: constructor_service
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - /usr/src/app/node_modules
